name: Feature Request
description: Suggest an idea for this project
title: '[Feat]: '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        We are working hard on the project, but we cannot think about everything. That's where you come into the game! We appreciate all feedback and feature requests!

  - type: textarea
    attributes:
      label: Is your feature request related to a problem you are experiencing?
      description: Provide as much information as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you would like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you have considered.
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context.
      description: Add any other information, or screenshot about your feature request.
    validations:
      required: false
