            - name: Doxygenize
  # You may pin to the exact commit or the version.
  # uses: langroodi/doxygenize@542946a13bc9021f5ba07c8751e6ab3d84bca154
  uses: langroodi/doxygenize@v1.7.0
  with:
    # Doxygen configuration file path
    doxygenconf: ./docs/Doxyfile
    htmloutput: ./docs/
    ghpagesbranch: gh-pages
    ghpagesdir: ./
    darkmode: yes
          
