name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch. Adjust if your default branch has a different name.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./
          token: ${{ secrets.GITHUB_TOKEN }} 
          
